@startuml
!theme plain

title Блок-схема процесса работы пациента

start
:Вход в систему;
:Заполнить данные о состоянии здоровья;
:Посмотреть данное назначение;

if (Лекарство было принято\nв соответствии с инструкциями?) then (да)
  :Отметить прием;
else (нет)
  :Указать причину пропуска\nи состояние здоровья;
endif

stop

@enduml