@startuml
!theme plain

title Блок-схема процесса работы медработника

start
:Вход в систему;

if (Есть ли пациент в базе данных?) then (нет)
  :Добавить пациента и\nиндивидуальные особенности;
  :Создать новое назначение;
else (да)
endif

:Назначить лекарственный препарат;
:Назначить продолжительность приема,\nвремя и дозировку;

if (У пациента отмечено\nухудшение самочувствия?) then (да)
  :Создать новое назначение;
else (нет)
endif

stop

@enduml












