@startuml
!theme plain

left to right direction

actor "Медработник" as Doctor
actor "Пациент" as Patient

rectangle "Система учета пациентов и лекарств" {
  ' Медработник
  usecase "Список всех пациентов" as UC1
  usecase "Просмотр назначений пациентов" as UC2
  usecase "Изменить назначение" as UC3
  usecase "Добавить историю болезни пациента" as UC4
  usecase "Добавить индивидуальные особенности пациента" as UC5
  usecase "Создать новое назначение" as UC6
  usecase "Просмотр статуса приема препаратов" as UC7
  usecase "Просмотр медицинской карты пациента" as UC8

  ' Пациент
  usecase "Отметить самочувствие после препарата" as UC9
  usecase "Подтвердить прием препаратов" as UC10
  usecase "Посмотреть назначенные препараты" as UC11
}

' Связи медработника с его функциями
Doctor --> UC1
Doctor --> UC2
Doctor --> UC3
Doctor --> UC4
Doctor --> UC5
Doctor --> UC6
Doctor --> UC7
Doctor --> UC8

' Связи пациента с его функциями
Patient --> UC9
Patient --> UC10
Patient --> UC11

@enduml